### ISSUE TITLE
Database: Colored category tags in results of colored categories (literature, fine arts, history, science)

### ISSUE THREAD

**Issue by ani-per** [qbreader/website#101]
Very minor feature request: it would add another feature for users' eyes to more easily distinguish results.

e.g. color (or highlight, which would be even better) the word "Literature" in "2022 PACE NSC | Literature | American Literature" with the hex `#0d6efd` in light mode and `#375a7f` in dark mode.

**Comment by geoffrey-wu** [comment]
Going to close this for now, as I don't really like how it looks (especially in conjunction with #94).
