### ISSUE TITLE
Database: Bold in-power text

### ISSUE THREAD

**Issue by ani-per** [qbreader/website#102]
Friedrich Nietzsche mocked an earlier writer for professing this attitude but playing the flute every day after dinner. A “strength”-oriented form of this attitude is described in The Birth of Tragedy, which is subtitled for “Hellenism” and this attitude. An Antonio Gramsci aphorism advocates this attitude “of the intellect,” and its opposite “of the will.” Concepts like “gratuitous violence” and “natal alienation” are adapted from Orlando Patterson’s work in Frank Wilderson’s book on an (*) “afro-” form of this attitude. The author of On the Fourfold Root of the Principle of Sufficient Reason is often seen as an exemplar of this attitude since he believed life was “blind striving” driven by the Will. For 10 points, Arthur Schopenhauer’s work features what attitude of expecting the worst from the world?

&darr;

**Friedrich Nietzsche mocked an earlier writer for professing this attitude but playing the flute every day after dinner. A “strength”-oriented form of this attitude is described in The Birth of Tragedy, which is subtitled for “Hellenism” and this attitude. An Antonio Gramsci aphorism advocates this attitude “of the intellect,” and its opposite “of the will.” Concepts like “gratuitous violence” and “natal alienation” are adapted from Orlando Patterson’s work in Frank Wilderson’s book on an (*)** “afro-” form of this attitude. The author of On the Fourfold Root of the Principle of Sufficient Reason is often seen as an exemplar of this attitude since he believed life was “blind striving” driven by the Will. For 10 points, Arthur Schopenhauer’s work features what attitude of expecting the worst from the world?

---

I think this'd be helpful - unless I'm missing something and there's a specific reason why this isn't preferable 😅

**Comment by brightly-salty** [comment]
I'd like to try to implement this if it's all right with Geoffrey, but I don't know if I can test on my device.

**Comment by geoffrey-wu** [comment]
Go for it
