### ISSUE TITLE
Database: Searching with set filter = 2022 QUARTET returns no results, even with no other filters active

### ISSUE THREAD

**Issue by ani-per** [qbreader/website#103]
![image](https://user-images.githubusercontent.com/49991597/203174843-e85d9962-9da7-4d0a-9040-b5b3691e05a1.png)

**Comment by geoffrey-wu** [comment]
Turns out this is caused by the use of the (less-preferred) lit subcategories "Long Fiction", "Short Fiction", "Poetry", and "Drama".
