### ISSUE TITLE
Avoid using `dangerouslySetInnerHTML` in the database page

### ISSUE THREAD

**Issue by alopezlago** [qbreader/website#108]
database\index.jsx uses `dangerouslySetInnerHTML` in a few places for formatting question text. This can be risky since any tags in the question could be interpreted as HTML. Instead, consider allowlisting a set of known tags (<b>, <i>, <u>, etc.) and use a special component to render the text. This way there's no security or formatting issues that can be introduced by packets.

**Comment by geoffrey-wu** [comment]
How would the special component render the text (without itself using dangerously set inner HLTML)?

**Comment by alopezlago** [comment]
One approach is to parse it and create an array of words, where each word has the formatting information. This is what MODAQ does (see [the parser](https://github.com/alopezlago/MODAQ/blob/master/src/parser/FormattedTextParser.ts) and the [React component](https://github.com/alopezlago/MODAQ/blob/master/src/components/FormattedText.tsx)). You control the server where the questions come from, so you can also send this information ahead of time if you don't want the client to do it. You can also reverse the data structure and just store a list of indexes and the change in formatting and add tags manually that way.
