### ISSUE TITLE
Some of the API endpoints don't seem to work

### ISSUE THREAD

**Issue by cpc2** [qbreader/website#112]
Some of the endpoints in https://www.qbreader.org/api-info don't seem to work as explained, for example the random-question for this:
https://www.qbreader.org/api/random-question?questionType=tossup
Returns Invalid question type specified.

Edit: nevermind, seems like instead of parameters you have to pass the json as payload. I feel like the wording should be updated in the docs. I'm not sure why it's a POST when it's retrieving data with params that could be passed directly as params like the other GET endpoints.

**Comment by geoffrey-wu** [comment]
Yes, I'm planning on changing it to GET instead of POST in the future, but for now you'll have to use POST.
