### ISSUE TITLE
Account System

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#127]
Allow people to make accounts. This would include the following features:

- Login system (and account creation)
- Allowing people to see their past queries
- Allowing people to see stats on questions or sets they've played
- Creation of leaderboard across accounts
- Admin system to manage database

**Comment by alopezlago** [comment]
Do you want to handle all of this in the app or use OAuth and offload most of it to an identity provider like Google or Microsoft ?

**Comment by geoffrey-wu** [comment]
I'm not sure—I'm more familiar with handling this in-app, but I've used OAuth before as well. Open to hearing suggestions about either, but I'm learning toward handling this in-app.

**Comment by geoffrey-wu** [comment]
Closed by 8f2c960b5b7d696b48bfe147acf4e86c8d1dd6b0
