### ISSUE TITLE
Track advanced stats

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#128]
Track advanced stats per question:

- For tossups, track average / median celerity, conversion data, and power rate
- For bonuses, track average conversion per part

This information could be useful or fun on its own, and it can also help guide writers and set editors.

**Comment by geoffrey-wu** [comment]
Could also have a thumbs-up / thumbs-down feature to rate questions. Would require implementing #127 first.

**Comment by JustAnotherStrange** [comment]
Hi - thanks for your work on this project, it's really great.

Something else like this could be tracking stats for each category in play.
Like power % for each category, celerity for each category...

Also, a suggestion, this stuff could be in a separate "advanced stats" menu so the main tossup screen doesn't become too crowded with numbers and stats. IDK though.

**Comment by alopezlago** [comment]
If you want this to be portable (not just using localStorage/IndexedDB), you'll need to finish #127 first

**Comment by geoffrey-wu** [comment]
Closed by 8f2c960b5b7d696b48bfe147acf4e86c8d1dd6b0
