### ISSUE TITLE
Saying "I was correct" in tossups

### ISSUE THREAD

**Issue by JustAnotherStrange** [qbreader/website#131]
The algorithm that decides whether or not your answer is correct is not 100% accurate, but that is not what this issue is about.

There is already the ability to say "I was wrong" if you are marked as right, but arguably more frustrating is when you are marked wrong but actually were correct if the answerline were interpreted correctly.

In single-player tossup mode, could there be added an "I was right" button when a tossup is answered in correctly?

Thanks for all the work on the program. It's really helpful.

**Comment by geoffrey-wu** [comment]
What would be the best way to implement this? I'm thinking either implement #125, or have two buttons for the user once the answer is revealed: "I was wrong", and "I was right", and "I was right" would mark the first buzz as correct and clear all the negs on that tossup.

**Comment by JustAnotherStrange** [comment]
I feel like both could work. The first one could be implemented along with the rebuzz toggle, and the second one could be integrated into the current mode.

Also, since the algorithm is accurate 95%+ of the time, I'd like to still not have to press any buttons for that 95%. It should only show the "I was right" or "I was wrong" depending on which one would be _correcting_ the algorithm. Therefore, on a neg, you could press "I was right," and on a correct answer, you could press "I was wrong."

For the second one, it would be a little trickier. The button to correct the algorithm would appear below after a question is complete. It would require "remembering" the buzzes, so it could be determined after the fact whether it's 10 or 15, and how many negs need to be removed. 

Thanks for responding so quickly.
