### ISSUE TITLE
Same token can be matched multiple times in `stringMatchesReference` (for evaluating answers)

### ISSUE THREAD

**Issue by alopezlago** [qbreader/website#132]
https://github.com/qbreader/website/blob/12f2e6842d48cae53fa2993a06b9212b06345f46/server/scorer.js#L428-L450

When comparing `stringTokens` against `referenceTokens` in Room.stringMatchesReference, we never remove the reference token that matches the string token. This means that the same reference token can match different string tokens. This will lead to inocrrect matches. For example, there will be a match when the reference string "Major Tom" is compared against the string "Major Major Major", even though they are different.

There are a few ways to do this. One way to do it is to keep track of the last reference token we should use, and when we find a matching reference token, we swap it with the token at the last position and decrease the number of reference tokens we check against.

**Comment by geoffrey-wu** [comment]
In a similar vein, token order should (probably) matter - i.e. "potential chemical" shouldn't match against "chemical potential". Probably easiest to keep an index for both arrays and increment them (never going backwards) to check for a match.

**Comment by geoffrey-wu** [comment]
For now, I'm going to assume that token order does not matter; otherwise, answers like "Australian Prime Minister" don't get accepted for "Prime Minister of Australia", for example.
