### ISSUE TITLE
Replace queryLock/queryUnlock with method that always unlocks after the action.

### ISSUE THREAD

**Issue by alopezlago** [qbreader/website#133]
As it's written, if `queryLock` or the method after it throws an exception, then `queryUnlock` won't be called and the user will be stuck.

One way to fix this is to make a method that takes in the function to run as an argument. Then it can call `queryLock`, and then run the action in a try/catch block that will run `queryUnlock` even if an exception is thrown.

**Comment by geoffrey-wu** [comment]
Tried implementing as suggested—but it didn't work (the buttons wouldn't disable). I suspect it's because of how the javascript event loop works (it tries to run all the javascript at once before pushing DOM changes).
