### ISSUE TITLE
Buzzer race bug seems to break lobby

### ISSUE THREAD

**Issue by g3ner1c** [qbreader/website#153]
![image](https://user-images.githubusercontent.com/74469257/230524742-2f0c2249-7c28-4f5e-8b44-d1f1dd6ac411.png)

After a buzzer race where both players seem to have lost with nobody getting the buzz, the game seems to be stuck in a limbo state where nobody seem to be rewarded the buzz. It's also impossible to skip the tossup while in this state, essentially suspending the lobby.

I don't exactly know what the cause of the bug is, nor do I know how to reproduce it.

**Comment by g3ner1c** [comment]
![image](https://user-images.githubusercontent.com/74469257/230530382-64499120-fde5-4b35-8cf9-af707889554d.png)
Another instance of the bug seemed to... fix itself?

**Comment by geoffrey-wu** [comment]
Not sure what's causing this bug but for the second instance, when you leave a room, it automatically negs you if you're buzzed in. I'll look more into this.

**Comment by geoffrey-wu** [comment]
Not sure what the cause is or how to reproduce. Will close this for now and reopen if it's a persistent issue.
