### ISSUE TITLE
Add filter for names in multiplayer

### ISSUE THREAD

**Issue by Elitemagikarp** [qbreader/website#155]
I have seen some pretty rude names

**Comment by geoffrey-wu** [comment]
Going to table this until after the [account system](https://github.com/qbreader/website/issues/127) is created and do some sort of manual review. (I'd maybe seek help from the community on this part, not sure how much time I would have to review usernames. What I have in mind is some sort of "report username" button). Judging by what I could find on the internet, there's [too](https://www.reddit.com/r/gamedesign/comments/ojcwfi/banned_usernames_dataset/) [many](http://www.bannedwordlist.com/) [issues](https://en.wikipedia.org/wiki/Scunthorpe_problem) with doing this algorithmically, and it would be very easy to circumvent.
