### ISSUE TITLE
Add a toggle for question skipping 

### ISSUE THREAD

**Issue by JustAnotherStrange** [qbreader/website#156]
This is especially useful for multiplayer, where two people pressing next at once can cause a question to be skipped.

**Comment by geoffrey-wu** [comment]
How would you be able to advance the question? In particular, would people only be able to skip questions when the toggle is on / when someone gets the question right.

**Comment by JustAnotherStrange** [comment]
The way protobowl manages this is there is a timer for the tossup to go dead, and the question can be advanced after it goes dead, someone gets it correct, or everyone gets it wrong (if no multi-buzzing).

A simpler way to do this, without a timer, would be to make it so anyone can advance the question once the tossup is finished being read.
Just no skipping while the question is still being read.
It wouldn't be as foolproof against accidental skips, but I think it would be much easier to implement, and more intuitive to users, than a timer system.

**Comment by geoffrey-wu** [comment]
That sounds great—I'll implement something like this first, and figure out the timer later (#121). In the same vein, if there are no rebuzzes on, it could be a useful idea to automatically show the question if everyone has buzzed incorrectly on the tossup.
