### ISSUE TITLE
Separate "Serious" and "Non-Serious" (trash) Quizbowl Packets

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#160]
This issue was inspired by the addition of the [gamerboy80 pack](https://trash.quizbowlpackets.com/2930/).

**Comment by Captain-Quack** [comment]
Sets like "The Last 1022 Years Were Boring Anyway" should also be separated

**Comment by geoffrey-wu** [comment]
Will probably make a switch to include/exclude vanity packets

**Comment by geoffrey-wu** [comment]
Could also consider filtering out single-subject sets

**Comment by Captain-Quack** [comment]
"Exclude Standard Format"?
