### ISSUE TITLE
Specify how 'Search by exact phrase' differs from normal searching

### ISSUE THREAD

**Issue by Captain-Quack** [qbreader/website#186]
I previously thought the characters were already matched literally when both regexp and diacritic switches were turned off. It might help to specify what turning the 'exact phrase' switch adds.

**Comment by geoffrey-wu** [comment]
I'll clarify this on the website; exact match in this case means that the word has to exactly match, so you can't have substrings. For example, with exact match on, searching "hydrogen" will not match against "**hydrogen**ation". This is similar to how aseemsdb works.

**Comment by Captain-Quack** [comment]
oh, that's cool.
