### ISSUE TITLE
API - Category requests not being respected in random-tossup

### ISSUE THREAD

**Issue by Luminoso-256** [qbreader/website#189]
Hello!

I've recently been using this API for something, and it was working fine up until a couple days ago. For whatever reason, category specification no longer seems to be respected when making a request to `/api/random-tossup`:

GET `qbreader.org/api/random-tossup` with the payload
```json
{
    "difficulties":[3],
    "categories":"Literature",
    "subcategories":[],
    "number":1
}
```

for example, has variably returned tossups in science, social science, etc. 
As far as I can tell I'm still using the correct format for the API request... if you have a rough idea of what might be causing the error I'd be happy to help try and fix it.

**Comment by geoffrey-wu** [comment]
Since it is a GET request, the body of the request is ignored. Using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) like
```js
const response = await fetch('https://www.qbreader.org/api/random-tossup?') new URLSearchParams({
    "difficulties":[3],
    "categories":"Literature",
    "subcategories":[],
    "number":1
})).then(response => response.json())
```
works for me.

**Comment by Luminoso-256** [comment]
Ah, that's my bad! Thanks
