### ISSUE TITLE
Download (txt/csv/json) includes only the 20 questions in the current pagination instead of all results

### ISSUE THREAD

**Issue by hftf** [qbreader/website#193]

**Comment by geoffrey-wu** [comment]
Currently, changing the pagination results in fetching a new query to the server, so this isn't supported. You can change the # to display field to get more results to show up on the current pagination (and thus increase the download size), or you can use the api endpoints or backups for larger queries.

**Comment by hftf** [comment]
Can the label for the link be changed to something like "Download questions on this page" then? The element of surprise is large when you expect a file with thousands of questions and there are only 20.

**Comment by geoffrey-wu** [comment]
I've gone ahead and made that change.
