### ISSUE TITLE
[idea] Lazy Load Database

### ISSUE THREAD

**Issue by Captain-Quack** [qbreader/website#199]
I recently learned about lazy loading and thought it might be a good idea for the qbreader database. Would loading the results as the user scrolled down make it faster?

That would also introduce some nice features like infinite scrolling.

**Comment by geoffrey-wu** [comment]
Could be more useful for larger queries? But for the default size of 25 it's probably not worth it. I'd also have to reconfigure the layout, since currently the bonuses are below the tossups (so infinite scrolling would make it really hard to get to bonuses).

**Comment by Captain-Quack** [comment]
That's true :(
