### ISSUE TITLE
Use typescript

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#206]
Could start with backend code and then work on frontend. Also, we would define types for all documents in the database (e.g. `Tossup`, `Bonus`) which could be useful to other developers. We could use [mongoose](https://mongoosejs.com/) for this?

**Comment by Captain-Quack** [comment]
I can help a bit, if you need some. (Pretty busy right now though)

**Comment by geoffrey-wu** [comment]
If you want to help with this, for organization purposes, try to keep everything to the typescript branch I just created

**Comment by Captain-Quack** [comment]
@geoffrey-wu I added a config file to help get started with the conversion. Hope it's helpful.

**Comment by geoffrey-wu** [comment]
Some thoughts after working on this for a bit:
1. I'm not really sure what the best file configuration is. Maybe having the `.js` and `.ts` files in the same place (instead of src/built) would be better? Routing with the current folder split feels "hacky".
2. Need to set up `eslint` for typescript
3. Could be helpful to incrementally adopt typescript (one file at a time) instead of trying to do the conversion at once - this would probably be easier with point 1.
4. Adding types is more work than I expected, even with a lot of types encoded in the JavaDoc. A way to automate this process (some online tool or GPT-4) is probably more ideal.

**Comment by Captain-Quack** [comment]
I was looking up some ways to do this, and it turns out [Stripe](https://stripe.com/blog/migrating-to-typescript) had this issue as well. 

AirBnB made a [migration](https://github.com/airbnb/ts-migrate) tool that looks promising...

Also, I was looking at [this](https://bun.sh) runtime tool that is supposed to be super fast - it could make-up for the performance lost by using typescript.

**Comment by geoffrey-wu** [comment]
Since the project is so well-established, it's probably not worth it to migrate the entire codebase to typescript. A better idea could be to use **JSdoc**, inspired partially by this Firebase video https://youtu.be/5ChkQKUzDCs?si=FjiJ3EdgvBG4lMuG this could easily be incrementally added and would require no breaking changes or build step.

**Comment by Captain-Quack** [comment]
Hmm, you're right, that might be better. 

P.S Fireship is a great channel!

**Comment by geoffrey-wu** [comment]
I'm likely going to close this issue after adding appropriate JSDoc to all the backend code (so everything in `database/` and `server/`).

**Comment by Captain-Quack** [comment]
Do you need help?

**Comment by geoffrey-wu** [comment]
> Do you need help finishing all of the JSDoc?

Yes, that would be helpful!

**Comment by Captain-Quack** [comment]
Oops, I totally slacked off on this, sorry!

**Comment by geoffrey-wu** [comment]
No worries, I think I'll drop this issue, since with the new eslint class import system it's pretty easy to determine the definition of something.
