### ISSUE TITLE
Regex Parameter Broken

### ISSUE THREAD

**Issue by eyloncaplan** [qbreader/website#217]
Hi I think the "regex" parameter for qbreader.org/api/query is not working. Everything else seems to work fine but based on my testing this does not. Thanks!

**Comment by eyloncaplan** [comment]
Also this causes the "Ignore Diacritics" option to break as well (since I think this option just uses a regex expression query).

**Comment by g3ner1c** [comment]
Can you describe more specifically what's broken? If you used a script or any code to query the api would you mind sharing it?

**Comment by eyloncaplan** [comment]
I figured it out! I was setting the regex parameter to the raw True value when I should have been sending "true" or "false" as a string! Very much my mistake, so I'll close this issue.
