### ISSUE TITLE
Lps/Livingston.qbreader

### ISSUE THREAD

**Issue by Neel214** [qbreader/website#219]
Hi I suggest making township servers. Our town is having a problem with impersonations and slurs and we are not able to find out who is doing them. I would like to have 2 or 3 servers where you have to login with your township email to join and use your real name.

**Comment by JeliHacker** [comment]
Not sure if this completely solves your issue, but there is a way to make rooms private by toggling "Public room" in the options. That way it won't appear in the list of public rooms, and you can send people the URL so they can join. 
I just opened a PR allowing people to make a room private when it is created.

**Comment by Neel214** [comment]
No we have a school private link but there is someone from our school
spamming so we neee to know who

**Comment by Neel214** [comment]
He is spamming the n word and continuesly raiding all priv links

**Comment by geoffrey-wu** [comment]
Sorry to hear that - perhaps you can try using a different (private) link? The closest feature I can think of to what you're asking for is to require users to enter the room with a verified account under a email of a certain domain (e.g. your township), but that would take some time to implement.

**Comment by Neel214** [comment]
If you could implement that in like a few months that would be great but
for now i will use a different private link. Thanks for your help.
