### ISSUE TITLE
Make db link change as query changes

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#222]

**Comment by Captain-Quack** [comment]
Are you thinking of caching the results of each query into some sort of link database? That could make frequent searches faster.

**Comment by geoffrey-wu** [comment]
Probably not? I was thinking something like where you can press the back button to go back to a previous search - it would be a client-side change.

**Comment by geoffrey-wu** [comment]
This could be useful: <https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState>[](url)
