### ISSUE TITLE
[Bug] Questions Skipping without Skip Command being input

### ISSUE THREAD

**Issue by IncoherentButter** [qbreader/website#229]
Bug:
Sometimes when I have skips enabled, I'll skip one question, and then the next few questions will suddenly skip after only a few lines have been read.  I'm not 100% sure, but this may be occurring after a question is prematurely skipped. For instance, in a private multiplayer room I was in, one user was hitting next after each question; when these unprompted skips occurred in that room, they were attributed to that same user (i.e. the chat said "<that user> went to the next question." This has also happened when I am playing solo in a private multiplayer room.

Settings when bug occurred:

- Multiplayer Room. Private enabled. 
- `Allow Skips` set to ON, `Enable Timer` set to ON. Error occurs with `Powermarked Tossups Only` set to ON or OFF.

**Comment by Captain-Quack** [comment]
(`Allow Rebuzzes` should also be off for replication.)
