### ISSUE TITLE
Move "math" subcategory to an alternate_subcategory under "Other Science"

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#233]
This would be more consistent with how [most sets](https://acf-quizbowl.com/distribution/#math-computer-science-astronomy-earth-science-) and [style guides](https://minkowski.space/quizbowl/manuals/style/packet.html#standard-tags) treat math.

**Comment by Captain-Quack** [comment]
Good idea, adding math would also balance the other science content with the other categories (Physics and Biology both have around 7,000 tossups, Chemistry has around 6,000, Math has ~2,000, and Other Science currently has ~5,000)
