### ISSUE TITLE
Sanitized Api Direct Request

### ISSUE THREAD

**Issue by Felix-Neat** [qbreader/website#325]
Would it be possible for the API requests to include a "../random-tossup-sanitized" to remove GET request difficulty.

**Comment by Felix-Neat** [comment]
I was thinking maybe you could add a url modifier to only get parts of the
JSON response. Like I know you can do it in the code after it’s recieved
but it would be pretty cool to avoid the hassle. I figured my project out
and I feel dumb about this but yeah.

**Comment by geoffrey-wu** [comment]
I see
