### ISSUE TITLE
Issue #327 but with buzzing again

### ISSUE THREAD

**Issue by thiyageshvenkat** [qbreader/website#328]
When I buzz(space bar), something very similar happens to closed issue #327 again. This might also occur for other actions as well.

**Comment by geoffrey-wu** [comment]
can you explain in more detail what actions you take for this to happen?

**Comment by thiyageshvenkat** [comment]
For example
I press space again although i have successful answered the question and the entire question is shown. Not answering correctly will continue the question from when I had previously buzzed.
"Allow rebuzzes" is enabled.

A citywide boycott in Liverpool of the newspaper The Sun was prompted by its coverage of a disaster in one of these places which killed 96 people. Ai (eye) Weiwei designed one of these structures in Beijing called the "Bird's Nest" (#) for the 2008 (*) Olympics. The ancient Panathinaikos, one of these structures in Athens, hosted many events during the first Olympic Games. For 10 points, what structures are used to host football games?(#) for the 2008 Olympics. The ancient Panathinaikos, one of these structures in Athens, hosted many events during the first Olympic Games. For 10 points, what structures are used to host football games?
