### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by geoffrey-wu** [qbreader/website#70]

**Comment by ADawesomeguy** [comment]
Can I please give this a shot? Like ESLint?

**Comment by geoffrey-wu** [comment]
Yep, that's exactly what I had in mind. Try to stick to whatever style I have currently:
- 4 space indent
- braces on newline after loop
- files end in newline

**Comment by ADawesomeguy** [comment]
Sir Geoffrey you have terrible tendencies but I will adhere nonetheless.

**Comment by geoffrey-wu** [comment]
Admittedly, when I began, I treated this like a project and not production code

**Comment by geoffrey-wu** [comment]
@ADawesomeguy Realized I had a typo—braces should be same line as loop

**Comment by ADawesomeguy** [comment]
Ok that makes me happier

**Comment by alopezlago** [comment]
It won't be your style but I find es/tslint + prettier an easy combination for linting and automatic code formatting.
