### ISSUE TITLE
Database: add dropdown checklist for difficulty value

### ISSUE THREAD

**Issue by ani-per** [qbreader/website#98]
Right now, the user can enter values between 1 and 10 to filter by difficulty. However:

1. It's unclear what these difficulty values represent exactly - does it use the quizdb system of 1 = middle school, 2 = easy high school, etc.[^1]?
2. It's not immediately clear if the user should type something like `1, 2, 3, 5` or something like `1235` instead (the former worked but it's not what first comes to mind for me)

Something that looks like the following checklist would be more intuitive as a dropdown:

- [ x ] 1 = Middle School
- [   ] 2 = Easy High School ...
- [ x ] 10 = Open

[^1]: I'm guessing it doesn't because QuizDB's scale only ranges from 1 to 9 inclusive.

**Comment by brightly-salty** [comment]
Possibly [ReactSelect](https://react-select.com/home) could be used for this? I assume the difficulty scale is as follows:

1 (Middle School)
2 (Easy High School)
3 (Regular High School)
4 (Hard High School)
5 (National High School)
6 (Easy College)
7 (Regular College)
8 (Hard College)
9 (??) -- maybe sub-open or National College? I see ACF Nationals and also sets like VICO, FlOpen which describe themselves as open
10 (Open)

With clarification as to what 9 entails, and if it's all right to use react-select, then I would like to try implementing this

**Comment by geoffrey-wu** [comment]
The difficulty scale for 1-5 is right, and 10 is open, but for 6-9, it follows [Ophir's dot scale](https://collegequizbowlcalendar.com/difficulty-scale/):

6: 1 dot / Easy College
7: 2 dot / Medium College
8: 3 dot / Regular College
9: 4 dot / Nationals College

React select looks perfect...and perhaps I could add this kind of dropdown to the other pages that use difficulty selection too.

**Comment by hftf** [comment]
I would recommend against using the label "Regular", especially if it's in reference to the college quizbowl calendar difficulty scale, which deliberately avoids the word entirely.

**Comment by geoffrey-wu** [comment]
Good call, I've updated my post to reflect this.

**Comment by hftf** [comment]
You just edited the comment above, right? What about the dropdowns and the about page on the website?

**Comment by geoffrey-wu** [comment]
The about page always used the word "Regular". See fcf9db261e57035cdc33a465352ce4a8d24e164b. I'm not sure if I'll use the dropdowns, but if I ever do, it will be updated there as well.
